### ISSUE TITLE
How do we test the function triggers that passes through the props?

### ISSUE THREAD

**Issue by hyochan** [testing-library/native-testing-library#101]
![image](https://user-images.githubusercontent.com/27461460/71794658-da54de00-3085-11ea-957b-02eea5888093.png)

I've been digging into to cover the above the uncovered line and I can't find a good answer from `stackoverflow`. Could you give me any idea?

I've been trying to mock `setSpinnerProps` with `jest.fn` but no luck.

1. Pressing then show spinner modal.
2. Pressing on cancel button when spinner modal appears.

```
  it('should cancel connection after pressing cancel when spinner pops up', async () => {
    jest
      .spyOn(SquareContext, 'useSquareContext')
      // @ts-ignore
      .mockImplementation(() => contextValues);

    testingLib = render(component);

    const btn = testingLib.queryByTestId('0');
    await wait(() => expect(btn).toBeTruthy());
    act(async () => {
      fireEvent.press(btn, 'press');
    });
    act(async () => {
      const btnModalCancel = testingLib.queryByTestId('test-modal-cancel');
      await wait(() => expect(btnModalCancel).toBeTruthy());
      act(() => {
        fireEvent.press(btnModalCancel, 'press');
      });
    });
  });
```

The `btnModalCancel` is always not defined

How should I mock `setSpinnerProps: jest.fn()` in above case?

**Comment by bcarroll22** [comment]
Hi, I don't have a ton of context for this, but it seems like what's happening may be a little off. My best guess is you may need to do something like this:

```
  it('should cancel connection after pressing cancel when spinner pops up', async () => {
    jest
      .spyOn(SquareContext, 'useSquareContext')
      .mockImplementation(() => contextValues);

    testingLib = render(component);

    // assuming this fires SquareListItem's onPress prop
    const btn = testingLib.queryByTestId('0');
    fireEvent.press(btn, 'press');
    expect(btn).toBeTruthy();

    // assuming this is the onCancel function
    const btnModalCancel = await testingLib.findByTestId('test-modal-cancel');
    fireEvent.press(btnModalCancel, 'press');
    expect(btnModalCancel).toBeTruthy();
  });
```

All of the extra `act` stuff you're doing, you shouldn't need to do it and it may actually be messing with the outcomes of your tests. You shouldn't really ever need to call `act` yourself, we take care of act behind the scenes. If you're still getting the warnings, you may want to upgrade versions of React/RN to get rid of them, but they likely aren't real problems... just warnings.

The other thing, there was a lot of `wait`-ing for async things that don't seem like they'd be async. That can also mess up the results of tests. Hopefully this helps!  Going to close as not an issue, but good luck!
