### ISSUE TITLE
Wrong import in cheat-sheet.pdf

### ISSUE THREAD

**Issue by iacopo87** [testing-library/native-testing-library#103]
Hello,

I saw that in the file `cheat-sheet.pdf` the import statement is:

`import { render } from ‘native-testing-library’;`

 instead of 

`import { render } from '@testing-library/react-native';`

so I think that is better if you update that document to match the rest of the documentation :)

**Comment by thymikee** [comment]
FYI, this repository is no longer responsible for this package. See the [migration guide to v7.0](https://callstack.github.io/react-native-testing-library/docs/migration-v7/). 
Please feel free to generate the cheat-sheet.pdf there :)
