### ISSUE TITLE
Unable to trigger onPress for TouchableWithoutFeedback from 'react-native-gesture-handler'

### ISSUE THREAD

**Issue by brockaflocka** [testing-library/native-testing-library#106]
- `react-native`
- `native-testing-library` version: ^5.0.3
- `jest-preset`: @testing-library/react-native
- `react-native` version: 0.61.4
- `node` version: 13.3.0

### Relevant code or config:

```js
// Trying to get this component to work (notice TouchableWithoutFeedback import)
// "pressed!" not being triggered here
import React, {useContext} from 'react';
import {Text, View} from 'react-native';
import {
  TouchableWithoutFeedback,
} from 'react-native-gesture-handler';
return (
    <>
      <TouchableWithoutFeedback
        testID="submitterCheck"
        onPress={() => console.log('pressed!')}
        }}>
         // Some components within this
      </TouchableWithoutFeedback>
    </>
  );

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This component works with 'TouchableWithoutFeedback' being imported from 'react-native'
import React, {useContext} from 'react';
import {Text, View,TouchableWithoutFeedback} from 'react-native';
return (
    <>
      <TouchableWithoutFeedback
        testID="submitterCheck"
        onPress={() => console.log('pressed!')}
        }}>
         // Some components within this
      </TouchableWithoutFeedback>
    </>
  );
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


  // Jest function that should trigger onPress()
  test('submitter form appears after submitter check', () => {
    const submitterCheckbox = getByTestId('submitterCheck');
    fireEvent.press(submitterCheckbox);
    expect(submitterName).toBeTruthy();
  });
```

### What you did:

During unit testing, I was using TouchableWithoutFeedback from the library 'react-native-gesture-handler rather than 'react-native'. Came across the issue where 'fireEvent' would not trigger the 'onPress' in 'TouchableWithoutFeedback'.

### What happened:

There's no trigger happening.

### Reproduction:

Code above describes what works and what doesn't. 

### Problem description:

N/A

### Suggested solution:

With react-native-gesture-handler versions of Touchables bypassing the JS rendering layer and hooking into native functionality, is this why the test engine does not have access to this trigger?

### Can you help us fix this issue by submitting a pull request?

N/A

**Comment by thymikee** [comment]
This shouldn't be a problem in v7.0.
FYI, this repository is no longer responsible for this package. See the [migration guide to v7.0](https://callstack.github.io/react-native-testing-library/docs/migration-v7/).
