### ISSUE TITLE
Invariant Violation when running through GitKraken

### ISSUE THREAD

**Issue by tobiaseisenschenk** [testing-library/native-testing-library#111]
- `react-native`: 0.61.4
- `native-testing-library` version: 5.0.3
- `jest-preset`: @testing-library/react-native + babel-jest + ts-jest
- `node` version: 12.14.0 (default + used by GitKraken)
- `GitKraken`: 6.5.1

### Relevant code or config:

```js
import { render, waitForElement } from '@testing-library/react-native';
import React from 'react';

const { queryByText } = render(<SomeComponent {...props} />);
```

### What you did:

Execute a pre-push commit hook (husky) through the GitKraken client.

### What happened:

```
● Test suite failed to run

    Invariant Violation: It is not supported to run the profiling version of a renderer (for example, `react-dom/profiling`) without also replacing the `scheduler/tracing` module with `scheduler/tracing-profiling`. Your bundler might have a setting for aliasing both modules. Learn more at http://fb.me/react-profiling

      at node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5502:9
      at node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:5494:3
      at Object.<anonymous> (node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:16:3)
      at Object.<anonymous> (node_modules/react-native/Libraries/Renderer/shims/ReactNative.js:18:17)
```

### Reproduction:

Possible, but I would like to explore the scope and ideas first.

### Problem description:

Our githooks fail because of what seems to be a combination of factors. There are related issues at [react](https://github.com/facebook/react/issues/16263) and [huskey](https://github.com/typicode/husky/issues/243), but none of the discussed points could resolve our issue. When executing tests through `npm test` or even through the githook after `git push` from the terminal all tests pass. However the only tests failing when running through GitKraken are those using `render` from this testing library. Therefore I am hoping that above error gives some indication.

**Comment by luisnomad** [comment]
Still happening... any workaround to fix this? We can't use GitKraken in our project because of this issue...

**Comment by chrisngabp** [comment]
I'm having the same issue... but locally. Any updates on this?

**Comment by thymikee** [comment]
FYI, this repository is no longer responsible for this package. See the [migration guide to v7.0](https://callstack.github.io/react-native-testing-library/docs/migration-v7/).
