### ISSUE TITLE
Preset with Expo in install doc is out of date

### ISSUE THREAD

**Issue by TaylorAbraham** [testing-library/native-testing-library#117]
- `react-native` or `expo`: Expo v36
- `native-testing-library` version: 5.0.3
- `jest-preset`: jest-expo (v36.0.1)
- `react-native` version: 36.0.1
- `node` version: v13.12.0
### Relevant code or config:

The install docs cite the following setup jest file for expo:
```
const expoPreset = require('jest-expo/jest-preset.json');
const jestPreset = require('@testing-library/react-native/jest-preset');

module.exports = Object.assign(expoPreset, jestPreset, {
  setupFiles: [...expoPreset.setupFiles, ...jestPreset.setupFiles, './mySetup.js'],
});
```

### What you did:
I followed these steps and could not figure out how to get this working for expo.

### What happened:
```
Error: Cannot find module 'jest-expo/jest-preset.json'
```

### Reproduction:
Using expo 36, follow the installation guide and use the jest config mentioned above.

### Problem description:
It seems that jest-expo changed the import such that you shouldn't put the '.json' at the end of the import. However, removing the .json does not fix the issue as jest will throw issues such as 'expect not defined', indicating the setup is still wrong.

### Suggested solution:
This setup works:
```
const jestPreset = require('@testing-library/react-native/jest-preset');

module.exports = {
  preset: 'jest-expo',
  setupFiles: [...jestPreset.setupFiles, './mySetup.js'],
};
```

### Can you help us fix this issue by submitting a pull request?
Yes! I don't mind making a PR with these changes.

**Comment by KiwiKilian** [comment]
The proposed config works for me, but throws the following warning:

```
react-native/jest-preset contained different transformIgnorePatterns than expected
Expected react-native/jest-preset to define transform[^.+\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp)$]
react-native/jest-preset contained different transformIgnorePatterns than expected
```

I don't have any additional setup like `mySetup.js` and use the following versions:
- `expo`: v37.0.8
- `native-testing-library`: v5.0.3
- `jest-expo`: v37.0.0
- `react-native`: v37.0.0
- `node`: v12.16.1

**Comment by AlanSl** [comment]
Proposed config fixes it for me too 👍 

Quick note that if you're using `react-native-web` and multi-platform / universal expo tests, including `...jestPreset.setupFiles` in the web setup caused tests to fail for me with this error:

> "Cannot find module '../Libraries/Image/Image'" from 'node_modules/react-native/jest/setup.js'

It looks like the testing-library config forces it to look somewhere that has `.ios` and `.android` files and stops it getting the `.web` version.

It works for me if I exclude those files from the `web` test run like:

```
const jestPreset = require('@testing-library/react-native/jest-preset');

const settings = {
 setupFiles: [/* files not including testing-library ones*/];
 ...
}

const nativeSetupFiles = [...jestPreset.setupFiles, ...settings.setupFiles]

const nativeSettings = {
  ...settings,
  setupFiles: nativeSetupFiles
}

module.exports = {
  projects: [
    { preset: 'jest-expo/web', ...settings },
    { preset: 'jest-expo/ios', ...nativeSettings },
    { preset: 'jest-expo/android', ...nativeSettings }
  ]
}
```

**Comment by thymikee** [comment]
FYI, this repository is no longer responsible for this package. See the [migration guide to v7.0](https://callstack.github.io/react-native-testing-library/docs/migration-v7/).
