### ISSUE TITLE
Support for fire Scrollview onScroll events

### ISSUE THREAD

**Issue by acollazomayer** [testing-library/native-testing-library#118]
**Describe the feature you'd like:**

It would be good to be able to fire onScrollEvents for scrollviews, flat list or even section lists.

**Suggested implementation:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by JongtaekChoi** [comment]
Does `fireEvent.scroll` not work?
https://github.com/testing-library/native-testing-library/blob/master/src/lib/events.js
