### ISSUE TITLE
How should drag events be simulated?

### ISSUE THREAD

**Issue by pabloKz** [testing-library/native-testing-library#122]
Hello!

I've been searching for a while in the Native Testing Library docs but couldn't find any example on how to test a drag action on react native. 

I know there's fireEvent[eventName] but none of the methods for draggable items (Scrollview for example) seem to have an example on how to implement them.

I'll be eager to help add some documentation around it but I can't find any way to make them work for myself at first. 

Any help would be greatly appreciated.

**Comment by thymikee** [comment]
It really depends on your implementation (e.g. using PanResponder or Gesture Handler) – which means it's better to write an end-to-end test for such functionality.
