### ISSUE TITLE
Support Installation via Git Dependency

### ISSUE THREAD

**Issue by phlmn** [testing-library/native-testing-library#137]
**Describe the feature you'd like:**

I would like to be able to install the library via Git instead of the npm registry. Currently this is not working since babel is only run before publishing.

**Suggested implementation:**

Change `prepublishOnly` script in package.json to `prepare`.

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

This should be fully compatible with the existing solution since it just adds the execution of the script on `npm install` (without arguments) and on git dependency installation. It will still be executed before publishing.

**Comment by thymikee** [comment]
FYI, this repository is no longer responsible for this package. See the [migration guide](https://callstack.github.io/react-native-testing-library/docs/migration-v7/).
