### ISSUE TITLE
Add upcoming deprecation to project README

### ISSUE THREAD

**Issue by ryanjwessel** [testing-library/native-testing-library#139]
**Describe the feature you'd like:**

[According to this GitHub Issue](https://github.com/callstack/react-native-testing-library/issues/442), this project is being deprecated in favor of [callstack/react-native-testing-library](https://github.com/callstack/react-native-testing-library). I think the README should be updated to reflect this so that people that are introducing Testing Library to their React Native project do not use the wrong dependency. Especially since this one is part of the official Testing Library group, it could lead to confusion.

**Suggested implementation:**

We could add something like this to the top of the README:

---

**DEPRECATION WARNING:**

This project is in the process of being deprecated in favor of [callstack/react-native-testing-library](https://github.com/callstack/react-native-testing-library). If you are adding Testing Library to a React Native project, please use that one instead. If you are using this project currently, we are working on a [migration guide](https://github.com/callstack/react-native-testing-library/issues/442) to assist you in switching dependencies.

---

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

N/A

---

I am happy to put up a Pull Request for this once we determine the exact wording we'd like to use.

**Comment by thymikee** [comment]
Happy to help with this one. I think the wording should focus on new users for now, to let them know that there's a different library they want to use. Once we have a migration guide, we can link that as well and provide to existing users.

**Comment by sibelius** [comment]
what are the motivations behind this?

**Comment by ryanjwessel** [comment]
That makes sense, thanks @thymikee. So, maybe something like this?

## Deprecation Warning

This project is being deprecated in favor of [callstack/react-native-testing-library](https://github.com/callstack/react-native-testing-library). You should use that library instead of this one. A migration guide is in development now for existing users of this library.

**Comment by ryanjwessel** [comment]
> what are the motivations behind this?

@sibelius I learned about this from [one of Kent's tweets](https://twitter.com/kentcdodds/status/1283815988496961537?s=20), and there is some context there.

**Comment by thymikee** [comment]
Done in c864cd573cd3ac9f40da8540d6ffbc6b8dc6aa52 :)
