### ISSUE TITLE
queryByTitle missing?

### ISSUE THREAD

**Issue by JanithaR** [testing-library/native-testing-library#144]
The documents talk about a `queryByTitle` [here](https://www.native-testing-library.com/docs/api-queries#bytitle). Yet when trying to use it I get the error,

> TypeError: queryByTitle is not a function

**Comment by thymikee** [comment]
FYI, this repository is no longer responsible for this package. See the [migration guide](https://callstack.github.io/react-native-testing-library/docs/migration-v7/).
In v7, we removed the `ByTitle` queries, so this is no longer applicable.
