### ISSUE TITLE
Test config not initialized in non-<rootdir> monorepo packages anymore

### ISSUE THREAD

**Issue by jpstrikesback** [testing-library/native-testing-library#18]
- `react-native`
- `native-testing-library` version: 3.0.0
- `jest-preset`: native-testing-library
- `react-native` version: 0.59.3
- `node` version: 12.2.0

### Relevant code or config:

```js
...example tests from docs
```

### What you did:

Ran a test in a shared package in a monorepo that worked before upgrading to 3.0.0

```js
roots: ['<rootDir>', '../shared'],
```

### What happened:

after upgrading from 2.x to 3.x all tests in the shared package that use getByText return the following error:

`"TypeError: Cannot read property 'includes' of undefined"`

when calling (in query-helpers.js):
```js
function validComponentFilter(node, key) {
  return key ? (0, _config.getConfig)(key).includes(node.type) : typeof node.type === 'string';
}
```

the issue is that the config key for `textComponents` is nowhere to be found.

### Problem description:

Tests in a shared folder in a monorepo previously ran fine. I would like to keep them where they are :)

### Suggested solution:

I haven't fully grokked yet, but it seems the config is called twice when another root is added, but the second time the call to configure() doesn't happen at all. My next step is to see if the react-native preset does anything similar that I can borrow to ensure all roots get the same treatment :D :D

**Comment by bcarroll22** [comment]
Hmm this is interesting, it'll be very hard for me to help debug this one since I don't have any monorepos to play around with. I'm not exactly sure how the monorepo would make a difference, but then again I've not really ever used one much. I'll do the best I can to help out!

I appreciate any help debugging this one. In the meantime, for you/your team's sake it might be worth it to downgrade to 2.0 in the meantime. 2.0 handles the react-native jest preset better than 3.0 does, so you'd get a lot more predictable behavior there.

**Comment by jpstrikesback** [comment]
Cheers! I'll keep debugging and share my findings or failures here :)

**Comment by bcarroll22** [comment]
Not sure why this would matter, or why it might help but can you try changing line 9 in `jest-preset.js` to:

```
setupFilesAfterEnv: [require.resolve('./dist/preset/setup.js')],
```

maybe it's being grouchy that the test environment isn't available yet for some reason?

**Comment by TAGraves** [comment]
I can try to dig into this some tomorrow - at Root we have monorepo tooling I can apply to our internal projects using NTL to see if we can reproduce. 

What are you using to manage your monorepo?

**Comment by jpstrikesback** [comment]
Just yarn workspaces.

OK, so, I seem to have fixed my issue!

I had a nohoist AND a devDependency in the root package.json for native-testing-library (due to an errant `yarn add -DW ...`. And it seems there were two copies of native-testing-library being picked up by jest when there were multiple roots specified. This only happened now (upon upgrade to 3.x) as:

Previously the react-native preset was blissfully alone because my react-native was nohoisted and only in the mobile package.json deps :)

Thanks for your attention, super appreciated!! Maybe this will help someone in the future who may encounter this :)

**Comment by sibelius** [comment]
@jpstrikesback do you have an example of monorepo working with this package?

**Comment by jpstrikesback** [comment]
Hey @sibelius, I've got a side project I'm chipping away at in a monorepo, which has the 3.x version working for the native side, I've just started to move on the web end of things (it's a TypeScript monorepo with RN & NextJS sharing RNWeb components).

I'll ping you on twitter with more details.

Cheers!
JP

**Comment by sibelius** [comment]
@jpstrikesback did you got any changes to open source this?

**Comment by jpstrikesback** [comment]
try this :) https://github.com/jpstrikesback/react-native-web-monorepo/tree/testing-library

(it's a fork of @brunolemos monorepo with testing-library for react-native and react(native-web) working)

**Comment by sibelius** [comment]
When I run `yarn jest` it does not work in your repo

```jsx
Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    SyntaxError: /opensource/react-native-web-monorepo/packages/mobile/__tests__/App-test.js: Unexpected token (14:18)

      12 | 
      13 | it('renders correctly', () => {
    > 14 |   renderer.create(<App />);
         |                   ^
      15 | });
      16 | 

      at Parser.raise (node_modules/@babel/parser/lib/index.js:6420:17)
      at Parser.unexpected (node_modules/@babel/parser/lib/index.js:7773:16)
      at Parser.parseExprAtom (node_modules/@babel/parser/lib/index.js:8996:20)
      at Parser.parseExprSubscripts (node_modules/@babel/parser/lib/index.js:8556:23)
      at Parser.parseMaybeUnary (node_modules/@babel/parser/lib/index.js:8536:21)
      at Parser.parseExprOps (node_modules/@babel/parser/lib/index.js:8402:23)
      at Parser.parseMaybeConditional (node_modules/@babel/parser/lib/index.js:8375:23)
      at Parser.parseMaybeAssign (node_modules/@babel/parser/lib/index.js:8325:21)
      at Parser.parseExprListItem (node_modules/@babel/parser/lib/index.js:9659:18)
      at Parser.parseCallExpressionArguments (node_modules/@babel/parser/lib/index.js:8774:22)
```

**Comment by jpstrikesback** [comment]
Hmm 🤔 that looks like the `master` branch, can you try in the `testing-library` branch?

**Comment by sibelius** [comment]
same error

it looks like only works inside `packages/web/` 

if you run `jest` from root it does not work

**Comment by jpstrikesback** [comment]
Ahah, it would definitely be preferable to run jest from the root on both, but currently I’m just running packages separately (in this repo) `yarn test` from the root will run a workspaces test CMD which will run jest in each package...
