### ISSUE TITLE
Typescript Error: findAllByTestId

### ISSUE THREAD

**Issue by AlexandreMPDias** [testing-library/native-testing-library#35]
- `react-native` or `expo`: expo
- `native-testing-library` version: 
- `jest-preset`: expo
- `react-native` version: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz
- `node` version: 10.11.0

### Relevant code or config:

```ts
	it('should render the typed password', () => {
		let login = render(<Login />);
		const emailField = login.findAllByTestId('login_email');
	//TODO
	});
```
### What happened:

I get a typescript error saying: "login_email" is not compatible with type 'MatcherOptions | undefined'.

### Issue

I read the source code... and the example in the documentations, and I think that the right type for this function's argument should be **Match**, as declared in **matches.d.ts**

### Workaround

If I write **'login_email' as any**, it works normally

**Comment by bcarroll22** [comment]
I believe this is related to https://github.com/testing-library/native-testing-library/pull/32

I don't use TypeScript personally or in any projects I work on, so I pretty much rely on folks who use this library and TypeScript to make sure that the typings work and are as accurate as possible. I'd appreciate any contributions you make to improving them! 😄

**Comment by AlexandreMPDias** [comment]
Ohh, I do think those are related... I specified "getByTestId" because I starting using this library yesterday and I had only used that function so far hahahah
