### ISSUE TITLE
`getByText` type might be wrong

### ISSUE THREAD

**Issue by wolverineks** [testing-library/native-testing-library#45]
- `expo`:
- `native-testing-library` version: 4.0.7
- `jest-preset`: jest-expo/jest-preset.js + @testing-library/react-native/jest-preset
- `react-native` version: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz
- `node` version: v12.5.0

### Relevant code or config:

```typescript
getByText(DISPLAY_STRINGS.page01.body, {
  // @ts-ignore
  normalizer: (string: string) => string.trim()
});
```

### What you did:

Tried to add options to `getByText`

### What happened:

Argument of type '{ normalizer: (string: string) => string; }' is not assignable to parameter of type 'WaitForElementOptions'.
  Object literal may only specify known properties, and 'normalizer' does not exist in type 'WaitForElementOptions'.ts(2345)

### Reproduction:

[demo](https://codesandbox.io/s/twilight-bush-ckwdj)

### Problem description:

This behavior doesn't match [documentation](https://www.native-testing-library.com/docs/api-queries#bytext)

### Suggested solution:

Update type, essentially,
```
- WaitForElementOptions
+ SelectorMatcherOptions
```

### Can you help us fix this issue by submitting a pull request?

I am able to submit a PR with the change

**Comment by bcarroll22** [comment]
@wolverineks sorry for the delay, I don't use TypeScript myself and generally rely on the community to maintain those types. Would you be willing to submit the PR for this? Thanks in advance!

**Comment by wolverineks** [comment]
np, ill take a whack at it when i get some time

**Comment by wolverineks** [comment]
im on it
