### ISSUE TITLE
`fireEvent.changeValue()` on Switch component doesn't work

### ISSUE THREAD

**Issue by teo029** [testing-library/native-testing-library#46]
Sorry for not having time to fill up the template, but there might be a problem with calling `fireEvent.changeValue()` on a react-native `Switch` component. I tried it for several hours and in several ways and the handler was not called (maybe others will find this useful).

I did change to react-native-testing-library where it worked.

**Comment by bcarroll22** [comment]
Thanks for calling this out, unfortunately without some more context from the issue template and a reproduction I won't be able to help much. We've not run into any issues with using the component in our tests (although I'll admit I'm not sure I've used a Switch with valueChange). 

If you or someone else running into this issue can help fill out the template and provide a simple reproduction case, I'd be happy to help!

**Comment by jeffreyffs** [comment]
Since I just filed another issue with Switch, I'm fairly certain this can be closed.

`fireEvent.valueChange(switchElement, true);` definitely works for Switch components. 

Maybe because you are using `fireEvent.changeValue()` (which isn't a function)

**Comment by teo029** [comment]
I switched to another library after trying it for several hours. I was using the correct function, although I might've mistaken its name here.

**Comment by Atomic71** [comment]
First of all, let me preface this comment with a huge thanks for this package! It's by far the most enjoyable testing tool I've encountred (Cypress is a close second.)

**Comment by jeffreyffs** [comment]
I'm not sure what to say:

![Screen Shot 2020-01-31 at 8 34 51 AM](https://user-images.githubusercontent.com/1441462/73556607-9cd53d80-4404-11ea-9dd1-7acf9f488223.png)

I'm also using react-native 0.61.5... but currently using 4.0.11 of native-testing-library

**Comment by belgamo** [comment]
It works with switch component, but what about Slider? I've tried but it doesn't works. I think as the `Slider` has the same event (`onValueChange`) it should work.
