### ISSUE TITLE
Update React and React Native dependencies to get async act

### ISSUE THREAD

**Issue by SophieAu** [testing-library/native-testing-library#60]
The React Native update to 0.61.1 was released in the last few days and it would be great if we could update to it to take advantage of things like `async act`.

Updating to the new versions should (in theory) not break anything since they are all minor versions. There might be some potential work involved in updating the `act` calls to allow for async acts (maybe wrapping everything into async act by default?).

**Comment by bcarroll22** [comment]
That would be awesome, can you submit a PR? Thanks for pointing it out!

**Comment by SophieAu** [comment]
just opened one here: https://github.com/testing-library/native-testing-library/pull/61 However I have added a few questions about how to handle the differentiation between using async or sync act in `render` and `fireEvent`
