### ISSUE TITLE
selector? option is not typed properly

### ISSUE THREAD

**Issue by ajsmth** [testing-library/native-testing-library#71]
Looks like this option is implemented with the namespace 'filter' rather than selector, and the typescript definition flags this. 

e.g in query-helpers.js: 
### Relevant code or config:

```js
function queryAllByProp(
  prop,
  container,
  match,
  { filter = n => n, exact = true, collapseWhitespace, trim, normalizer } = {},
) { ... }
```

### What you did:

I tried using the selector option for one of my custom queries

### Reproduction:

Example: 

```js
test.only('selector? bug', () => {
  const { baseElement, debug } = ntlRender(
    <Text accessibilityLabel="Hi" accessibilityStates={['disabled']}>
      Hi
    </Text>
  );

  // always finds because selector is not recognized as a filter
  const alwaysFinds = getByLabelText(baseElement, 'Hi', {
    selector: ({ props }) => props.acessibilityStates.includes('selected'),
  });

  debug(alwaysFinds);

  const willFind = getByLabelText(baseElement, 'Hi', {
    // @ts-ignore
    filter: ({ props }) => props.accessibilityStates.includes('disabled'),
  });

  debug(willFind);

  // throws as expected:
  const willNotFind = getByLabelText(baseElement, 'Hi', {
    // @ts-ignore
    filter: ({ props }) => props.accessibilityStates.includes('selected'),
  });

  debug(willNotFind);
});


```

### Problem description:

I think this is just a naming issue between `filter` and `selector`

### Suggested solution:

Either update the implementation to change the named parameter to be `selector` or update the typings / docs to reflect that the name should be `filter`

### Can you help us fix this issue by submitting a pull request?

Yup

**Comment by bcarroll22** [comment]
Nice, if you can help troubleshoot this and get a PR up, I'll get it merged ASAP 👍 Thanks for pointing it out!

**Comment by ajsmth** [comment]
yup no problem -- do you prefer keeping the `filter` option or should I change it to `selector`? when i checked there was only ~3 functions with the filter named argument to update

**Comment by bcarroll22** [comment]
We should change it to `selector` to make sure it's consistent with the API of the rest of testing library ([see here](https://testing-library.com/docs/dom-testing-library/api-queries#bylabeltext)).
