### ISSUE TITLE
TS error after update TS to version 3.7

### ISSUE THREAD

**Issue by serzmerz** [testing-library/native-testing-library#80]
- `native-testing-library` version: 5.0.0
- `typescript` version: 3.7.2

### What you did:

Upgrade ts to version 3.7.2

### What happened:

I faced with error: 

```
node_modules/@testing-library/react-native/typings/query-helpers.d.ts:1:10 - error TS2440: Import declaration conflicts with local declaration of 'ReactTestInstance'.

1 import { ReactTestInstance } from 'react-test-renderer';
           ~~~~~~~~~~~~~~~~~


Found 1 error.
```
It is related to change in TS 3.7:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#local-and-imported-type-declarations-now-conflict

### Problem description:

In ts 3.7 local and imported declarations now conflict, so we need to extend and rename types with the same name.

### Suggested solution:

I suggest to rename and extend interfaces in file query-helpers.d.ts
Actually, I found this PR: https://github.com/testing-library/native-testing-library/pull/79
could you merge it?

### Can you help us fix this issue by submitting a pull request?

Yes, but PR is exist https://github.com/testing-library/native-testing-library/pull/79.

**Comment by bcarroll22** [comment]
Closing now since this was fixed by the PR you referenced. Thanks!

Closed #79
