### ISSUE TITLE
improve debug omitProps option

### ISSUE THREAD

**Issue by sibelius** [testing-library/native-testing-library#88]
**Describe the feature you'd like:**

related to this one https://github.com/testing-library/native-testing-library/pull/70

but I'd like to go deep

We are using Relay in our app, and each fragment has a `__fragmentOwner` data that could be very large

we want to remove this `__fragmentOwner` and even more inside props when pretty printing with debug() calls

examples:

```jsx
sections={
                        Array [
                          Object {
                            "data": Array [
                              Object {
                                "node": Object {
                                  "__fragmentOwner": Object {
                                    "identifier": "query MyestQuery(
....

this is very big (more than 100 lines in terminal)

}>
```

**Suggested implementation:**

We can have something like this a sanitizeObject/value that run on value of props - similar to this one https://github.com/entria/entria-fullstack/blob/master/packages/server/test/helper.js#L131

it is a recursive solution

**Describe alternatives you've considered:**

another solution would be to omit the whole prop all together

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by bcarroll22** [comment]
Hmm I’m not sure I want that feature to get that heavy. Let me think about it for a while. 

My thought process right now is, this helper isn’t really intended to read or parse your props, just filter specific ones out. If you don’t want to see that huge output, it seems like you could just filter `sections` out of debug, right? It just seems like it’s a little out of scope 🤔

 @TAGraves what do you think?

One last thing now that I’m thinking about it, unless it’s passing the sections prop to host nodes it shouldn’t be in debug output anyways. Only things like View and Text should be in debug, what components are the fragments even being included in?
