### ISSUE TITLE
Picker component does not get value updated

### ISSUE THREAD

**Issue by vinipachecov** [testing-library/native-testing-library#93]
I'm having trouble changing the value of a native Picker component to test a component I've built on my own that uses the react-native Picker. 
Observing that calling fireEvent.valueChange did trigger the onValueChange callback, I was intrigued why  wasn't my hook useState wasn't been updated if it worked in the ios and android simulator.

I decided to test the example given in the React Native docs, but it also did not work.

source of the example: https://facebook.github.io/react-native/docs/picker

My component code:

```ts

export class PickerComponent extends React.Component {
  state = {
    language: '',
  };
  render() {
    return (
      <Picker
        accessibilityLabel="picker-ios"
        selectedValue={this.state.language}
        style={{ height: 50, width: 100 }}
        onValueChange={(itemValue, itemIndex) =>
          this.setState({ language: itemValue })
        }>
        <Picker.Item label="Java" value="java" />
        <Picker.Item label="JavaScript" value="js" />
      </Picker>
    );
  }
}
```

Jest example

```ts
it('should  render and change the selectedItem' , () => {
    const { getByLabelText } = render(<PickerComponent />);
    const Picker = getByLabelText('picker-ios');
    fireEvent.valueChange(Picker, items[0]);
    console.log(Picker);    
```

Testing it I observed that somehow the onValueChange callback is triggered but no update is done after calling it.

**Comment by bcarroll22** [comment]
I'm going to close this, can you please reopen using one of the provided issue templates including all of the versions, repros, etc. to help me out with triage? Thanks! 👍
