### ISSUE TITLE
Picker onValueChange callback not working

### ISSUE THREAD

**Issue by vinipachecov** [testing-library/native-testing-library#95]
<!-

- react-native:
- `native-testing-library` version: @testing-library/react-native": "^5.0.1"
- `jest-preset`: "preset": "@testing-library/react-native"
- `react-native` version: 0.61.4
- `node` version: 13.2.0

### Relevant code or config:
I'm having trouble changing the value of a native Picker component to test a component I've built on my own that uses the react-native Picker.
Observing that calling fireEvent.valueChange did trigger the onValueChange callback, I was intrigued why wasn't my hook useState wasn't been updated if it worked in the ios and android simulator.

I decided to test the example given in the React Native docs, but it also did not work.

source of the example: https://facebook.github.io/react-native/docs/picker

My component code:
```ts
export class PickerComponent extends React.Component {
  state = {
    language: ''",
  };
  render() {
    return (
      <Picker
        accessibilityLabel="picker-ios"
        selectedValue={this.state.language}
        style={{ height: 50, width: 100 }}
        onValueChange={(itemValue, itemIndex) =>
          this.setState({ language: itemValue })
        }>
        <Picker.Item label="Java" value="java" />
        <Picker.Item label="JavaScript" value="js" />
      </Picker>
    );
  }
}
```
Jest example

```js
it('should  render and change the selectedItem' , () => {
    const { getByLabelText } = render(<PickerComponent />);
    const Picker = getByLabelText('picker-ios');
    fireEvent.valueChange(Picker, items[0]);
    console.log(Picker);    
```
Testing it I observed that somehow the onValueChange callback is triggered but no update is done after calling it.

### What you did:
Tested Picker component on OSX with react native.

### What happened:
Doesn't update component status after changing values.

There is no error, it just doesn't update on Jest.
### Reproduction:

This is the minimum code required

```ts
export class PickerComponent extends React.Component {
  state = {
    language: '',
  };
  render() {
    return (
      <Picker
        accessibilityLabel="picker-ios"
        selectedValue={this.state.language}
        style={{ height: 50, width: 100 }}
        onValueChange={(itemValue, itemIndex) =>
          this.setState({ language: itemValue })
        }>
        <Picker.Item label="Java" value="java" />
        <Picker.Item label="JavaScript" value="js" />
      </Picker>
    );
  }
}
```
Jest example

```
it('should  render and change the selectedItem' , () => {
    const { getByLabelText } = render(<PickerComponent />);
    const Picker = getByLabelText('picker-ios');
    fireEvent.valueChange(Picker, items[0]);
    console.log(Picker);    
})
```

### Problem description:
When testing [Picker component](https://facebook.github.io/react-native/docs/picker)  with the lib, using fireEvent with valueChange calls the Picker change value callback but doesn't update the state in the tested component.

### Suggested solution:
Probably some inner problem related to the library itself.

### Can you help us fix this issue by submitting a pull request?
Yes, but no idea where to start.

**Comment by bcarroll22** [comment]
Hi, I can't reproduce this so I'm not sure what's going on. I ran this test:

```
test("that <Picker /> works", () => {
  const { debug, getByDisplayValue, getByLabelText } = render(<PickerComponent />);
  const Picker = getByLabelText('picker-ios');
  debug(Picker);
  fireEvent.valueChange(Picker, 'java');
  debug(Picker);
  getByDisplayValue('java');
});

```

and this was the output I got:

```
 PASS  src/__tests__/misc.js
  ● Console

    console.log src/index.js:44
      <Picker
        accessibilityLabel="picker-ios"
        mode="dialog"
        selectedValue=""
        style={
          Object {
            "height": 50,
            "width": 100,
          }
        }
      >
        <Picker.Item
          label="Java"
          value="java"
        />
        <Picker.Item
          label="JavaScript"
          value="js"
        />
      </Picker>
    console.log src/index.js:44
      <Picker
        accessibilityLabel="picker-ios"
        mode="dialog"
        selectedValue="java"
        style={
          Object {
            "height": 50,
            "width": 100,
          }
        }
      >
        <Picker.Item
          label="Java"
          value="java"
        />
        <Picker.Item
          label="JavaScript"
          value="js"
        />
      </Picker>

```

As you can see here, it correctly updates the selected value of the Picker. What happens if you run the test I pasted here?

**Comment by vinipachecov** [comment]
The test passes but does not change the selected Value in the Picker component.

**Comment by vinipachecov** [comment]
Thank you so much!! 

I've realized that the problem was the way I was sending the value with the api method valueChange(component, { itemprops....}).
onValueChange is a callback with 2 values (value, itemIndex) as I could not find a way to get the index, I decided to switch and find the item in my array of items using the value as a map.

**Comment by bcarroll22** [comment]
No problem, good luck! 👍
