### ISSUE TITLE
prettyPrint could take debug options when element was not found

### ISSUE THREAD

**Issue by sibelius** [testing-library/native-testing-library#96]
- `react-native` or `expo`: react-native
- `native-testing-library` version: 5.0.1
- `jest-preset`: native-testing-library
- `react-native` version: 0.61.0
- `node` version: 12.4.0

### Relevant code or config:

```js
expect(getByText('myText')).toBeTruthy();
```

### What you did:

Try to find a text that is not in the native nodes

### What happened:

it showed the debug() output but without take `debug` omitProps into consideration

### Problem description:

it should always take `debug` options in consideration when printing the native nodes

### Suggested solution:

pass `debug` to `getQueriesForElement` https://github.com/testing-library/native-testing-library/blob/a8ba4166942072ee420e2c77b7e377a605481e6b/src/index.js#L54

### Can you help us fix this issue by submitting a pull request?

I'll try

**Comment by thymikee** [comment]
FYI, this repository is no longer responsible for this package. See the [migration guide to v7.0](https://callstack.github.io/react-native-testing-library/docs/migration-v7/).
